# Generated by Django 2.1.3 on 2018-12-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Наименование категории'),
        ),
    ]
