# Generated by Django 2.1.3 on 2018-12-20 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20181220_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.Category', verbose_name='Наименование категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=15, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Наименование товара'),
        ),
    ]
